#define IDD_TEXTINPUTDIALOG				200
#define IDD_CONVERTDIALOG				300
#define IDD_CONVERTVIADIALOG			400
#define IDD_TEXTAREADIALOG				500
#define IDD_SORTOPTIONSDIALOG			600
#define IDD_REMOVEVIADIALOG				700
#define IDD_IMPORTVIADIALOG				800
